apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-data
  namespace: ntfy
  labels:
    app.kubernetes.io/name: ntfy
    app.kubernetes.io/component: notifications
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-zpool
  resources:
    requests:
      storage: 1Gi
