apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-subdir-external-provisioner
spec:
  interval: 15m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.18"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: nfs-subdir-external-provisioner
      interval: 1h
  values:
    nfs:
      server: "${nfsServer}"
      path: "${nfsPath}"

    storageClass:
      name: nfs-client
      defaultClass: false
      accessModes: ReadWriteOnce
      reclaimPolicy: Delete
      archiveOnDelete: true

    replicaCount: 1
