apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy-data
  namespace: wg-easy
  labels:
    app.kubernetes.io/name: wg-easy
    app.kubernetes.io/component: vpn
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-zpool
  resources:
    requests:
      storage: 512Mi
