apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: proxmox-csi-plugin
    namespace: csi-proxmox
  values:
    config:
      clusters:
        - url: "${proxmoxUrl}"
          insecure: ${proxmoxInsecure}
          token_id: "${proxmoxTokenId}"
          token_secret: "${proxmoxTokenSecret}"
          region: "${proxmoxRegion}"

    storageClass:
      - name: proxmox-zpool
        storage: zpool
        reclaimPolicy: Delete
        fstype: ext4
        ssd: true
        cache: writeback
