apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  interval: 1h
  url: https://github.com/sergelogvinov/proxmox-csi-plugin
  ref:
    tag: v0.17.1
