apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: "1.20.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 1h
  values:
    txtOwnerId: ${clusterName}
    provider: rfc2136
    rfc2136:
      host: "172.21.21.21"
      port: 53
      zone: "krebiehl.com."
      tsigSecretAlg: "hmac-sha512"
      tsigKeyname: "krebiehl.com."
    env:
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: external-dns-tsig
            key: rfc2136_tsig_secret
