apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: "8.8.0"
      sourceRef:
        kind: OCIRepository
        name: external-dns
        namespace: external-dns
      interval: 1h
  values:
    provider: rfc2136
    txtOwnerId: ${clusterName}
    rfc2136:
      host: "172.21.21.21"
      port: 53
      zone: "krebiehl.com."
      tsigKeyname: "krebiehl.com."
      tsigSecretAlg: "hmac-sha512"
      tsigAxfr: true
      secretName: "external-dns-tsig"
