apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/external-dns
  ref:
    tag: 8.8.0
