apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 15m
  chart:
    spec:
      chart: plex-media-server
      version: "1.4.0"
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: plex
      interval: 1h
  values:
    # Plex configuration
    timezone: America/New_York

    # Use the "public" image tag - this tag downloads the latest Plex Server version during startup
    image:
      tag: public

    # Storage configuration - use proxmox-zpool storage class
    pms:
      storageClassName: proxmox-zpool
      configStorage: 150Gi

    # Service configuration
    service:
      type: LoadBalancer
      port: 32400

    # Resource limits
    resources:
      requests:
        memory: 512Mi
        cpu: 500m

    # Init container for library migration
    extraInitContainers:
      - name: library-extractor
        image: alpine:3.19
        command:
          - /bin/sh
          - -c
          - |
            #!/bin/sh
            set -e

            ARCHIVE="/config/plex-library.tar.gz"
            LIBRARY_DIR="/config/Library"

            echo "=== Plex Library Migration Init Container ==="

            # Check if Library directory already exists
            if [ -d "$LIBRARY_DIR" ]; then
              echo "Library directory already exists - skipping extraction"
              exit 0
            fi

            # Check if migration archive exists
            if [ ! -f "$ARCHIVE" ]; then
              echo "No migration archive found at $ARCHIVE - skipping extraction"
              echo "This is normal for first-time startup"
              exit 0
            fi

            echo "Migration archive found: $ARCHIVE"
            echo "Extracting library data..."

            # Extract archive
            tar xzf "$ARCHIVE" -C /config/

            # Verify extraction
            if [ -d "$LIBRARY_DIR" ]; then
              echo "Library extracted successfully!"

              # Remove archive after successful extraction
              rm -f "$ARCHIVE"
              echo "Migration archive removed"
            else
              echo "ERROR: Library directory not found after extraction"
              exit 1
            fi

            echo "=== Migration complete - starting Plex ==="
        volumeMounts:
          - name: pms-config
            mountPath: /config

    # NFS volumes for media library and optimized media
    extraVolumes:
      - name: media
        nfs:
          server: diskstation.krebiehl.com
          path: /volume1/plex
          readOnly: true
      - name: optimized
        nfs:
          server: diskstation.krebiehl.com
          path: /volume1/plex-optimized
          readOnly: false

    extraVolumeMounts:
      - name: media
        mountPath: /media/library
        readOnly: true
      - name: optimized
        mountPath: /media/optimized
        readOnly: false

    # Ingress configuration (optional - update hostname as needed)
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: plex.krebiehl.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: plex-tls
          hosts:
            - plex.krebiehl.com
