apiVersion: v1
kind: ServiceAccount
metadata:
  name: plex-restart
  namespace: plex
  labels:
    app.kubernetes.io/name: plex
    app.kubernetes.io/component: restart-job
    app.kubernetes.io/managed-by: kustomize
