apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: "1.19.2"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      interval: 1h
  values:
    installCRDs: true
    extraArgs:
      - --dns01-recursive-nameservers-only
      # bypass local DNS resolvers that may not be able to resolve public DNS records
      - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
