apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: azure-secret-store
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/azure-secret-store
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
