apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/cert-manager-issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomizations
  dependsOn:
    - name: cert-manager
    - name: azure-secret-store
