apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomizations
  dependsOn:
    - name: azure-secret-store
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
