apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-address-pool
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/metallb-address-pool
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomizations
  dependsOn:
    - name: metallb
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
