apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/nfs-subdir-external-provisioner
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomizations
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
