apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: proxmox-csi-plugin
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/proxmox-csi-plugin
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomizations
  postBuild:
    substituteFrom:
      - kind: Secret
        name: proxmox-csi-plugin
