apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wg-easy
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/wg-easy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomizations
  dependsOn:
    - name: metallb
